"""init

Revision ID: 006691eeef8c
Revises: 
Create Date: 2026-03-03 15:58:16.675617

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '006691eeef8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prop_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('고유번호', sa.Text(), nullable=True),
    sa.Column('층', sa.Text(), nullable=True),
    sa.Column('형태', sa.Text(), nullable=True),
    sa.Column('평수', sa.Float(), nullable=True),
    sa.Column('보증금', sa.Integer(), nullable=True),
    sa.Column('임대료', sa.Integer(), nullable=True),
    sa.Column('월관리비', sa.Integer(), nullable=True),
    sa.Column('임대차기간', sa.Text(), nullable=True),
    sa.Column('공실유무', sa.Boolean(), nullable=True),
    sa.Column('생성일', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('고유번호', '층', name='uix_prop_addr_floor')
    )
    op.create_table('prop_main',
    sa.Column('매물번호', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('고유번호', sa.Text(), nullable=True),
    sa.Column('담당자', sa.Text(), nullable=True),
    sa.Column('진행상태', sa.Text(), nullable=True),
    sa.Column('매매가', sa.Numeric(), nullable=True),
    sa.Column('대지면적평단가', sa.Numeric(), nullable=True),
    sa.Column('연면적평단가', sa.Numeric(), nullable=True),
    sa.Column('총보증금', sa.Numeric(), nullable=True),
    sa.Column('총월세부가세별도', sa.Numeric(), nullable=True),
    sa.Column('총관리비', sa.Numeric(), nullable=True),
    sa.Column('수익률', sa.Float(), nullable=True),
    sa.Column('공실제외수익률', sa.Float(), nullable=True),
    sa.Column('자기자본수익률', sa.Float(), nullable=True),
    sa.Column('자기자본', sa.Numeric(), nullable=True),
    sa.Column('이자율', sa.Float(), nullable=True),
    sa.Column('긴급도', sa.Text(), nullable=True),
    sa.Column('등급', sa.Text(), nullable=True),
    sa.Column('입지', sa.Text(), nullable=True),
    sa.Column('건물용도', sa.Text(), nullable=True),
    sa.Column('사진', sa.Text(), nullable=True),
    sa.Column('브리핑', sa.Text(), nullable=True),
    sa.Column('명도', sa.Text(), nullable=True),
    sa.Column('멸실', sa.Text(), nullable=True),
    sa.Column('용도변경', sa.Text(), nullable=True),
    sa.Column('소유자타입', sa.Text(), nullable=True),
    sa.Column('소유자명', sa.Text(), nullable=True),
    sa.Column('전화번호', sa.Text(), nullable=True),
    sa.Column('성향', sa.Text(), nullable=True),
    sa.Column('관계', sa.Text(), nullable=True),
    sa.Column('접수일', sa.Date(), nullable=True),
    sa.Column('영상번호분초', sa.Text(), nullable=True),
    sa.Column('매수의향서', sa.Text(), nullable=True),
    sa.Column('빌탐정광고등록유무', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('매물번호'),
    sa.UniqueConstraint('고유번호')
    )
    op.create_table('seoul_land_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('고유번호', sa.Text(), nullable=True),
    sa.Column('시도', sa.Text(), nullable=True),
    sa.Column('시군구', sa.Text(), nullable=True),
    sa.Column('주소', sa.Text(), nullable=True),
    sa.Column('지목', sa.Text(), nullable=True),
    sa.Column('토지이용상황', sa.Text(), nullable=True),
    sa.Column('형상', sa.Text(), nullable=True),
    sa.Column('도로', sa.Text(), nullable=True),
    sa.Column('토지면적', sa.Float(), nullable=True),
    sa.Column('대지면적', sa.Float(), nullable=True),
    sa.Column('연면적', sa.Float(), nullable=True),
    sa.Column('건축면적', sa.Float(), nullable=True),
    sa.Column('용적률산정연면적', sa.Float(), nullable=True),
    sa.Column('규모지상', sa.Integer(), nullable=True),
    sa.Column('규모지하', sa.Integer(), nullable=True),
    sa.Column('엘리베이터', sa.Integer(), nullable=True),
    sa.Column('주차장', sa.Integer(), nullable=True),
    sa.Column('사용승인일', sa.Text(), nullable=True),
    sa.Column('대수선및리모델링', sa.Text(), nullable=True),
    sa.Column('용도지역', sa.Text(), nullable=True),
    sa.Column('주용도', sa.Text(), nullable=True),
    sa.Column('기타용도', sa.Text(), nullable=True),
    sa.Column('건폐율', sa.Float(), nullable=True),
    sa.Column('법정건폐율', sa.Float(), nullable=True),
    sa.Column('용적률', sa.Float(), nullable=True),
    sa.Column('법정용적률', sa.Float(), nullable=True),
    sa.Column('공시지가', sa.Numeric(), nullable=True),
    sa.Column('공시지가5년전', sa.Numeric(), nullable=True),
    sa.Column('공시지가10년전', sa.Numeric(), nullable=True),
    sa.Column('공시지가상승률5년전', sa.Float(), nullable=True),
    sa.Column('공시지가상승률10년전', sa.Float(), nullable=True),
    sa.Column('건폐율법정건폐율', sa.Float(), nullable=True),
    sa.Column('용적률법정용적률', sa.Float(), nullable=True),
    sa.Column('공시지가합계', sa.Numeric(), nullable=True),
    sa.Column('공시지가기준', sa.Numeric(), nullable=True),
    sa.Column('총공시지가와매매가비율', sa.Float(), nullable=True),
    sa.Column('AI추정가', sa.Text(), nullable=True),
    sa.Column('AI추정가매매가비율', sa.Float(), nullable=True),
    sa.Column('네이버광고', sa.Numeric(), nullable=True),
    sa.Column('네이버광고과거', sa.Numeric(), nullable=True),
    sa.Column('네이버광고상승률', sa.Float(), nullable=True),
    sa.Column('매각일1', sa.Text(), nullable=True),
    sa.Column('매각일2', sa.Text(), nullable=True),
    sa.Column('매각일3', sa.Text(), nullable=True),
    sa.Column('매각액1', sa.Numeric(), nullable=True),
    sa.Column('매각액2', sa.Numeric(), nullable=True),
    sa.Column('매각액3', sa.Numeric(), nullable=True),
    sa.Column('매각손익률', sa.Float(), nullable=True),
    sa.Column('소유자현재', sa.Text(), nullable=True),
    sa.Column('소유자과거', sa.Text(), nullable=True),
    sa.Column('x', sa.Float(precision=53), nullable=True),
    sa.Column('y', sa.Float(precision=53), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('고유번호')
    )
    with op.batch_alter_table('seoul_land_info', schema=None) as batch_op:
        batch_op.create_index('idx_seoul_land_info_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index('idx_seoul_land_info_pnu', ['고유번호'], unique=False)

    op.create_table('teams',
    sa.Column('master_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('master_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('user_pw', sa.Text(), nullable=True),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('belong_to_team', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['belong_to_team'], ['teams.master_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('prop_memos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pnu', sa.Text(), nullable=False),
    sa.Column('writer_id', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('importance', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['seoul_land_info.고유번호'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('setting_key', sa.Text(), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'setting_key', name='_user_setting_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('prop_memos')
    op.drop_table('users')
    op.drop_table('teams')
    with op.batch_alter_table('seoul_land_info', schema=None) as batch_op:
        batch_op.drop_index('idx_seoul_land_info_pnu')
        batch_op.drop_index('idx_seoul_land_info_geom', postgresql_using='gist')

    op.drop_table('seoul_land_info')
    op.drop_table('prop_main')
    op.drop_table('prop_details')
    # ### end Alembic commands ###
