"""add trgm

Revision ID: 45b51d64868a
Revises: afff78b4dcd6
Create Date: 2026-03-14 10:48:55.818071

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '45b51d64868a'
down_revision = 'afff78b4dcd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_main', schema=None) as batch_op:
        batch_op.create_index('idx_trgm_manager', ['담당자'], unique=False, postgresql_using='gist', postgresql_ops={'담당자': 'gist_trgm_ops'})

    with op.batch_alter_table('seoul_land_info', schema=None) as batch_op:
        batch_op.create_index('idx_trgm_address', ['주소'], unique=False, postgresql_using='gist', postgresql_ops={'주소': 'gist_trgm_ops'})
        batch_op.create_index('idx_trgm_owner_current', ['소유자현재'], unique=False, postgresql_using='gist', postgresql_ops={'소유자현재': 'gist_trgm_ops'})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seoul_land_info', schema=None) as batch_op:
        batch_op.drop_index('idx_trgm_owner_current', postgresql_using='gist', postgresql_ops={'소유자현재': 'gist_trgm_ops'})
        batch_op.drop_index('idx_trgm_address', postgresql_using='gist', postgresql_ops={'주소': 'gist_trgm_ops'})

    with op.batch_alter_table('prop_main', schema=None) as batch_op:
        batch_op.drop_index('idx_trgm_manager', postgresql_using='gist', postgresql_ops={'담당자': 'gist_trgm_ops'})

    # ### end Alembic commands ###
