"""db 리팩토링

Revision ID: 9b32d959e194
Revises: 
Create Date: 2026-01-26 18:10:10.248157

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9b32d959e194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prop_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('통합주소', sa.Text(), nullable=True),
    sa.Column('층', sa.Text(), nullable=True),
    sa.Column('정렬층', sa.Integer(), nullable=True),
    sa.Column('형태', sa.Text(), nullable=True),
    sa.Column('평수', sa.Float(), nullable=True),
    sa.Column('보증금', sa.Integer(), nullable=True),
    sa.Column('임대료', sa.Integer(), nullable=True),
    sa.Column('월관리비', sa.Integer(), nullable=True),
    sa.Column('임대차기간', sa.Text(), nullable=True),
    sa.Column('생성일', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('통합주소', '층', name='uix_prop_addr_floor')
    )
    with op.batch_alter_table('prop_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prop_details_통합주소'), ['통합주소'], unique=False)

    op.create_table('seoul_land_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('통합주소', sa.Text(), nullable=True),
    sa.Column('고유번호', sa.Text(), nullable=True),
    sa.Column('토지이용상황', sa.Text(), nullable=True),
    sa.Column('시도', sa.Text(), nullable=True),
    sa.Column('시군구', sa.Text(), nullable=True),
    sa.Column('주소', sa.Text(), nullable=True),
    sa.Column('지목', sa.Text(), nullable=True),
    sa.Column('형상', sa.Text(), nullable=True),
    sa.Column('도로', sa.Text(), nullable=True),
    sa.Column('대지면적', sa.Float(), nullable=True),
    sa.Column('연면적', sa.Float(), nullable=True),
    sa.Column('건축면적', sa.Float(), nullable=True),
    sa.Column('용도지역', sa.Text(), nullable=True),
    sa.Column('주용도', sa.Text(), nullable=True),
    sa.Column('기타용도', sa.Text(), nullable=True),
    sa.Column('건폐율', sa.Float(), nullable=True),
    sa.Column('법정건폐율', sa.Float(), nullable=True),
    sa.Column('용적률', sa.Float(), nullable=True),
    sa.Column('법정용적률', sa.Float(), nullable=True),
    sa.Column('용적률산정연면적', sa.Float(), nullable=True),
    sa.Column('규모지상', sa.Integer(), nullable=True),
    sa.Column('규모지하', sa.Integer(), nullable=True),
    sa.Column('엘리베이터', sa.Integer(), nullable=True),
    sa.Column('주차장', sa.Integer(), nullable=True),
    sa.Column('사용승인일', sa.Date(), nullable=True),
    sa.Column('대수선및리모델링', sa.Date(), nullable=True),
    sa.Column('공시지가', sa.Numeric(), nullable=True),
    sa.Column('공시지가5년전', sa.Numeric(), nullable=True),
    sa.Column('공시지가10년전', sa.Numeric(), nullable=True),
    sa.Column('공시지가기준', sa.Float(), nullable=True),
    sa.Column('매매가억', sa.Numeric(), nullable=True),
    sa.Column('상황', sa.Text(), nullable=True),
    sa.Column('긴급도', sa.Text(), nullable=True),
    sa.Column('등급', sa.Text(), nullable=True),
    sa.Column('컨디션', sa.Text(), nullable=True),
    sa.Column('입지', sa.Text(), nullable=True),
    sa.Column('매수의향서', sa.Text(), nullable=True),
    sa.Column('연락처', sa.Text(), nullable=True),
    sa.Column('성향', sa.Text(), nullable=True),
    sa.Column('관계', sa.Text(), nullable=True),
    sa.Column('사진', sa.Text(), nullable=True),
    sa.Column('브리핑', sa.Text(), nullable=True),
    sa.Column('두꺼비광고등록유무', sa.Text(), nullable=True),
    sa.Column('건물용도', sa.Text(), nullable=True),
    sa.Column('신축비용', sa.Numeric(), nullable=True),
    sa.Column('리모델링비용', sa.Text(), nullable=True),
    sa.Column('지주상황', sa.Text(), nullable=True),
    sa.Column('명도', sa.Text(), nullable=True),
    sa.Column('용도변경', sa.Text(), nullable=True),
    sa.Column('멸실', sa.Text(), nullable=True),
    sa.Column('영상번호분초', sa.Text(), nullable=True),
    sa.Column('AI추정가', sa.Text(), nullable=True),
    sa.Column('총보증금', sa.Numeric(), nullable=True),
    sa.Column('총월세부가세별도', sa.Numeric(), nullable=True),
    sa.Column('총관리비', sa.Numeric(), nullable=True),
    sa.Column('수익률', sa.Float(), nullable=True),
    sa.Column('네이버광고', sa.Numeric(), nullable=True),
    sa.Column('네이버광고과거', sa.Numeric(), nullable=True),
    sa.Column('매각액1', sa.Numeric(), nullable=True),
    sa.Column('매각일1', sa.Integer(), nullable=True),
    sa.Column('매각액2', sa.Numeric(), nullable=True),
    sa.Column('매각일2', sa.Integer(), nullable=True),
    sa.Column('매각액3', sa.Numeric(), nullable=True),
    sa.Column('매각일3', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(precision=53), nullable=True),
    sa.Column('y', sa.Float(precision=53), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seoul_land_info', schema=None) as batch_op:
        batch_op.create_index('idx_seoul_land_info_address', ['통합주소'], unique=False)
        batch_op.create_index('idx_seoul_land_info_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index('ix_seoul_land_info_x', ['x'], unique=False)
        batch_op.create_index('ix_seoul_land_info_y', ['y'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seoul_land_info', schema=None) as batch_op:
        batch_op.drop_index('ix_seoul_land_info_y')
        batch_op.drop_index('ix_seoul_land_info_x')
        batch_op.drop_index('idx_seoul_land_info_geom', postgresql_using='gist')
        batch_op.drop_index('idx_seoul_land_info_address')

    op.drop_table('seoul_land_info')
    with op.batch_alter_table('prop_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prop_details_통합주소'))

    op.drop_table('prop_details')
    # ### end Alembic commands ###
