"""db upgrade & 연면적당임대료 추가

Revision ID: afff78b4dcd6
Revises: 006691eeef8c
Create Date: 2026-03-12 10:24:12.542973

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'afff78b4dcd6'
down_revision = '006691eeef8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_details', schema=None) as batch_op:
        batch_op.alter_column('공실유무',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index('idx_prop_details_pnu', ['고유번호'], unique=False)

    with op.batch_alter_table('prop_main', schema=None) as batch_op:
        batch_op.add_column(sa.Column('공실유무총괄', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('연면적당임대료', sa.Numeric(), nullable=True))
        batch_op.create_index('idx_prop_main_pnu', ['고유번호'], unique=False)
        batch_op.create_index('idx_prop_main_price', ['매매가'], unique=False)
        batch_op.create_index('idx_prop_main_yield', ['수익률'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_main', schema=None) as batch_op:
        batch_op.drop_index('idx_prop_main_yield')
        batch_op.drop_index('idx_prop_main_price')
        batch_op.drop_index('idx_prop_main_pnu')
        batch_op.drop_column('연면적당임대료')
        batch_op.drop_column('공실유무총괄')

    with op.batch_alter_table('prop_details', schema=None) as batch_op:
        batch_op.drop_index('idx_prop_details_pnu')
        batch_op.alter_column('공실유무',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
