"""pnu idx 추가

Revision ID: ea422867646e
Revises: 9b32d959e194
Create Date: 2026-01-26 21:07:47.453435

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ea422867646e'
down_revision = '9b32d959e194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seoul_land_info', schema=None) as batch_op:
        batch_op.create_index('idx_seoul_land_info_pnu', ['고유번호'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seoul_land_info', schema=None) as batch_op:
        batch_op.drop_index('idx_seoul_land_info_pnu')

    # ### end Alembic commands ###
